import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';
import '../models/agreement_model.dart';
import '../repositories/agreement_repository.dart';
import '../core/constants/app_constants.dart';

class AgreementWizardState {
  final String documentType;
  final String offerNumber;
  final DateTime date;
  final String customerName;
  final String completeAddress;
  final String contactPerson;
  final String mobileNumber;
  final List<DescriptionItem> descriptionItems;
  final bool gstRequired;
  final double gstPercentage;
  final File? customerSignature;
  
  final int currentStep;
  final bool isSubmitting;
  final String? error;
  final AgreementModel? submittedAgreement;

  AgreementWizardState({
    required this.documentType,
    required this.offerNumber,
    required this.date,
    required this.customerName,
    required this.completeAddress,
    required this.contactPerson,
    required this.mobileNumber,
    required this.descriptionItems,
    required this.gstRequired,
    required this.gstPercentage,
    this.customerSignature,
    required this.currentStep,
    required this.isSubmitting,
    this.error,
    this.submittedAgreement,
  });

  factory AgreementWizardState.initial() {
    return AgreementWizardState(
      documentType: 'Agreement',
      offerNumber: 'Generated by server',
      date: DateTime.now(),
      customerName: '',
      completeAddress: '',
      contactPerson: '',
      mobileNumber: '',
      descriptionItems: [],
      gstRequired: false,
      gstPercentage: 18.0,
      customerSignature: null,
      currentStep: 0,
      isSubmitting: false,
      error: null,
      submittedAgreement: null,
    );
  }

  // Calculations for UI feedback
  double get totalBeforeGST {
    return descriptionItems.fold(0.0, (sum, item) => sum + item.subTotal);
  }

  double get gstAmount {
    return gstRequired ? (totalBeforeGST * gstPercentage) / 100.0 : 0.0;
  }

  double get grandTotal {
    return totalBeforeGST + gstAmount;
  }

  AgreementWizardState copyWith({
    String? documentType,
    String? offerNumber,
    DateTime? date,
    String? customerName,
    String? completeAddress,
    String? contactPerson,
    String? mobileNumber,
    List<DescriptionItem>? descriptionItems,
    bool? gstRequired,
    double? gstPercentage,
    File? customerSignature,
    int? currentStep,
    bool? isSubmitting,
    String? error,
    AgreementModel? submittedAgreement,
  }) {
    return AgreementWizardState(
      documentType: documentType ?? this.documentType,
      offerNumber: offerNumber ?? this.offerNumber,
      date: date ?? this.date,
      customerName: customerName ?? this.customerName,
      completeAddress: completeAddress ?? this.completeAddress,
      contactPerson: contactPerson ?? this.contactPerson,
      mobileNumber: mobileNumber ?? this.mobileNumber,
      descriptionItems: descriptionItems ?? this.descriptionItems,
      gstRequired: gstRequired ?? this.gstRequired,
      gstPercentage: gstPercentage ?? this.gstPercentage,
      customerSignature: customerSignature ?? this.customerSignature,
      currentStep: currentStep ?? this.currentStep,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      error: error, // Can reset to null if not passed
      submittedAgreement: submittedAgreement ?? this.submittedAgreement,
    );
  }

  AgreementModel toAgreementModel({String technicianSignatureUrl = kDefaultTechnicianSignatureUrl}) {
    return AgreementModel(
      documentType: documentType,
      date: date,
      customerName: customerName,
      completeAddress: completeAddress,
      contactPerson: contactPerson,
      mobileNumber: mobileNumber,
      descriptionItems: descriptionItems,
      gstRequired: gstRequired,
      gstPercentage: gstRequired ? gstPercentage : 0.0,
      totalBeforeGST: totalBeforeGST,
      gstAmount: gstAmount,
      grandTotal: grandTotal,
      technicianSignatureUrl: technicianSignatureUrl,
    );
  }
}

class AgreementWizardNotifier extends StateNotifier<AgreementWizardState> {
  final AgreementRepository _repository;

  AgreementWizardNotifier(this._repository) : super(AgreementWizardState.initial());

  void reset() {
    state = AgreementWizardState.initial();
  }

  void updateStep(int step) {
    state = state.copyWith(currentStep: step);
  }

  void updateDocumentType(String type) {
    state = state.copyWith(documentType: type);
  }

  void updateDate(DateTime date) {
    state = state.copyWith(date: date);
  }

  void updateCustomerName(String name) {
    state = state.copyWith(customerName: name);
  }

  void updateCompleteAddress(String address) {
    state = state.copyWith(completeAddress: address);
  }

  void updateContactPerson(String person) {
    state = state.copyWith(contactPerson: person);
  }

  void updateMobileNumber(String number) {
    state = state.copyWith(mobileNumber: number);
  }

  void updateGstRequired(bool required) {
    state = state.copyWith(gstRequired: required);
  }

  void updateGstPercentage(double pct) {
    state = state.copyWith(gstPercentage: pct);
  }

  void updateCustomerSignature(File? file) {
    state = state.copyWith(customerSignature: file);
  }

  void addDescriptionItem(DescriptionItem item) {
    state = state.copyWith(
      descriptionItems: [...state.descriptionItems, item],
    );
  }

  void removeDescriptionItem(int index) {
    final list = [...state.descriptionItems];
    list.removeAt(index);
    state = state.copyWith(descriptionItems: list);
  }

  void updateDescriptionItem(int index, DescriptionItem item) {
    final list = [...state.descriptionItems];
    list[index] = item;
    state = state.copyWith(descriptionItems: list);
  }

  bool validateCurrentStep(BuildContext context) {
    state = state.copyWith(error: null);

    switch (state.currentStep) {
      case 0: // Document Info
        if (state.documentType.isEmpty) {
          state = state.copyWith(error: 'Please select a document type.');
          return false;
        }
        return true;
      case 1: // Customer Info
        if (state.customerName.trim().isEmpty) {
          state = state.copyWith(error: 'Customer name is required.');
          return false;
        }
        if (state.completeAddress.trim().isEmpty) {
          state = state.copyWith(error: 'Complete address is required.');
          return false;
        }
        if (state.contactPerson.trim().isEmpty) {
          state = state.copyWith(error: 'Contact person name is required.');
          return false;
        }
        if (state.mobileNumber.trim().isEmpty) {
          state = state.copyWith(error: 'Mobile number is required.');
          return false;
        }
        return true;
      case 2: // Description Items
        if (state.descriptionItems.isEmpty) {
          state = state.copyWith(error: 'Please add at least one description item.');
          return false;
        }
        for (final item in state.descriptionItems) {
          if (item.description.trim().isEmpty) {
            state = state.copyWith(error: 'Item description cannot be empty.');
            return false;
          }
          if (item.quantity <= 0) {
            state = state.copyWith(error: 'Item quantity must be greater than zero.');
            return false;
          }
          if (item.rate <= 0) {
            state = state.copyWith(error: 'Item rate must be greater than zero.');
            return false;
          }
        }
        return true;
      case 3: // GST
        if (state.gstRequired && (state.gstPercentage < 0 || state.gstPercentage > 100)) {
          state = state.copyWith(error: 'GST percentage must be between 0 and 100.');
          return false;
        }
        return true;
      case 4: // Customer Signature
        if (state.customerSignature == null) {
          state = state.copyWith(error: 'Customer signature is required.');
          return false;
        }
        return true;
      default:
        return true;
    }
  }

  Future<bool> submitAgreement(String selectedDocType) async {
    state = state.copyWith(
      isSubmitting: true,
      error: null,
      documentType: selectedDocType,
    );

    try {
      final agreementModel = state.toAgreementModel();
      final result = await _repository.createAgreement(
        agreement: agreementModel,
        signatureFile: state.customerSignature!,
      );

      state = state.copyWith(
        isSubmitting: false,
        submittedAgreement: result,
      );
      return true;
    } catch (e) {
      state = state.copyWith(
        isSubmitting: false,
        error: e.toString(),
      );
      return false;
    }
  }
}

final agreementWizardProvider = StateNotifierProvider<AgreementWizardNotifier, AgreementWizardState>((ref) {
  final repo = ref.watch(agreementRepositoryProvider);
  return AgreementWizardNotifier(repo);
});
