import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';
import '../models/agreement_model.dart';
import '../repositories/agreement_repository.dart';
import '../core/constants/app_constants.dart';
import 'agreements_provider.dart';

class AgreementWizardState {
  final String? id;
  final String status; // 'draft' or 'submitted'
  final String documentType;
  final String offerNumber;
  final DateTime date;
  final String customerName;
  final String completeAddress;
  final String contactPerson;
  final String mobileNumber;
  final List<DescriptionItem> descriptionItems;
  final bool gstRequired;
  final double gstPercentage;
  final File? customerSignature;
  final int numberOfFreeVisits;
  
  final int currentStep;
  final bool isSubmitting;
  final String? error;
  final AgreementModel? submittedAgreement;

  AgreementWizardState({
    this.id,
    required this.status,
    required this.documentType,
    required this.offerNumber,
    required this.date,
    required this.customerName,
    required this.completeAddress,
    required this.contactPerson,
    required this.mobileNumber,
    required this.descriptionItems,
    required this.gstRequired,
    required this.gstPercentage,
    this.customerSignature,
    required this.numberOfFreeVisits,
    required this.currentStep,
    required this.isSubmitting,
    this.error,
    this.submittedAgreement,
  });

  factory AgreementWizardState.initial() {
    return AgreementWizardState(
      id: null,
      status: 'draft',
      documentType: 'Agreement',
      offerNumber: 'Generated by server',
      date: DateTime.now(),
      customerName: '',
      completeAddress: '',
      contactPerson: '',
      mobileNumber: '',
      descriptionItems: [],
      gstRequired: false,
      gstPercentage: 18.0,
      customerSignature: null,
      numberOfFreeVisits: 6,
      currentStep: 0,
      isSubmitting: false,
      error: null,
      submittedAgreement: null,
    );
  }

  // Calculations for UI feedback
  double get totalBeforeGST {
    return descriptionItems.fold(0.0, (sum, item) => sum + item.subTotal);
  }

  double get gstAmount {
    return gstRequired ? (totalBeforeGST * gstPercentage) / 100.0 : 0.0;
  }

  double get grandTotal {
    return totalBeforeGST + gstAmount;
  }

  AgreementWizardState copyWith({
    String? id,
    String? status,
    String? documentType,
    String? offerNumber,
    DateTime? date,
    String? customerName,
    String? completeAddress,
    String? contactPerson,
    String? mobileNumber,
    List<DescriptionItem>? descriptionItems,
    bool? gstRequired,
    double? gstPercentage,
    File? customerSignature,
    int? numberOfFreeVisits,
    int? currentStep,
    bool? isSubmitting,
    String? error,
    AgreementModel? submittedAgreement,
  }) {
    return AgreementWizardState(
      id: id ?? this.id,
      status: status ?? this.status,
      documentType: documentType ?? this.documentType,
      offerNumber: offerNumber ?? this.offerNumber,
      date: date ?? this.date,
      customerName: customerName ?? this.customerName,
      completeAddress: completeAddress ?? this.completeAddress,
      contactPerson: contactPerson ?? this.contactPerson,
      mobileNumber: mobileNumber ?? this.mobileNumber,
      descriptionItems: descriptionItems ?? this.descriptionItems,
      gstRequired: gstRequired ?? this.gstRequired,
      gstPercentage: gstPercentage ?? this.gstPercentage,
      customerSignature: customerSignature ?? this.customerSignature,
      numberOfFreeVisits: numberOfFreeVisits ?? this.numberOfFreeVisits,
      currentStep: currentStep ?? this.currentStep,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      error: error, // Can reset to null if not passed
      submittedAgreement: submittedAgreement ?? this.submittedAgreement,
    );
  }

  AgreementModel toAgreementModel({
    String technicianSignatureUrl = kDefaultTechnicianSignatureUrl,
    String? status,
  }) {
    return AgreementModel(
      id: id,
      status: status ?? this.status,
      documentType: documentType,
      date: date,
      customerName: customerName,
      completeAddress: completeAddress,
      contactPerson: contactPerson,
      mobileNumber: mobileNumber,
      descriptionItems: descriptionItems,
      gstRequired: gstRequired,
      gstPercentage: gstRequired ? gstPercentage : 0.0,
      totalBeforeGST: totalBeforeGST,
      gstAmount: gstAmount,
      grandTotal: grandTotal,
      numberOfFreeVisits: numberOfFreeVisits,
      technicianSignatureUrl: technicianSignatureUrl,
      customerSignatureUrl: customerSignature?.path,
    );
  }
}

class AgreementWizardNotifier extends StateNotifier<AgreementWizardState> {
  final AgreementRepository _repository;
  final AgreementsNotifier _agreementsNotifier;

  AgreementWizardNotifier(this._repository, this._agreementsNotifier) : super(AgreementWizardState.initial());

  void reset() {
    state = AgreementWizardState.initial();
  }

  void loadFromAgreement(AgreementModel agreement) {
    state = AgreementWizardState(
      id: agreement.id,
      status: agreement.status,
      documentType: agreement.documentType,
      offerNumber: agreement.offerNumber ?? 'Generated by server',
      date: agreement.date,
      customerName: agreement.customerName,
      completeAddress: agreement.completeAddress,
      contactPerson: agreement.contactPerson,
      mobileNumber: agreement.mobileNumber,
      descriptionItems: agreement.descriptionItems,
      gstRequired: agreement.gstRequired,
      gstPercentage: agreement.gstPercentage,
      numberOfFreeVisits: agreement.numberOfFreeVisits,
      customerSignature: agreement.customerSignatureUrl != null && agreement.customerSignatureUrl!.isNotEmpty && !agreement.customerSignatureUrl!.startsWith('http')
          ? File(agreement.customerSignatureUrl!)
          : null,
      currentStep: 0,
      isSubmitting: false,
      error: null,
      submittedAgreement: null,
    );
  }

  Future<bool> saveAsDraft() async {
    state = state.copyWith(isSubmitting: true, error: null);
    try {
      final agreementPayload = state.toAgreementModel(status: 'draft');
      
      AgreementModel result;
      if (state.id != null) {
        result = await _repository.updateAgreement(
          id: state.id!,
          agreement: agreementPayload,
          signatureFile: state.customerSignature,
        );
      } else {
        result = await _repository.createAgreement(
          agreement: agreementPayload,
          signatureFile: state.customerSignature,
        );
      }

      state = state.copyWith(
        isSubmitting: false,
        id: result.id,
        status: 'draft',
        offerNumber: result.offerNumber ?? 'Generated by server',
        submittedAgreement: result,
      );

      await _agreementsNotifier.refresh();
      return true;
    } catch (e) {
      state = state.copyWith(
        isSubmitting: false,
        error: e.toString(),
      );
      return false;
    }
  }

  void updateStep(int step) {
    state = state.copyWith(currentStep: step);
  }

  // Setters
  void updateDocumentType(String type) => state = state.copyWith(documentType: type);
  void updateDate(DateTime date) => state = state.copyWith(date: date);
  void updateCustomerName(String name) => state = state.copyWith(customerName: name);
  void updateCompleteAddress(String address) => state = state.copyWith(completeAddress: address);
  void updateContactPerson(String person) => state = state.copyWith(contactPerson: person);
  void updateMobileNumber(String number) => state = state.copyWith(mobileNumber: number);
  void updateGstRequired(bool isRequired) {
    state = state.copyWith(gstRequired: isRequired);
  }
  void updateGstPercentage(double pct) => state = state.copyWith(gstPercentage: pct);
  void updateNumberOfFreeVisits(int visits) => state = state.copyWith(numberOfFreeVisits: visits);
  void updateCustomerSignature(File? signature) => state = state.copyWith(customerSignature: signature);

  // Description Item helpers
  void addDescriptionItem(DescriptionItem item) {
    final list = [...state.descriptionItems, item];
    state = state.copyWith(descriptionItems: list);
  }

  void removeDescriptionItem(int index) {
    final list = List<DescriptionItem>.from(state.descriptionItems)..removeAt(index);
    state = state.copyWith(descriptionItems: list);
  }

  bool validateCurrentStep(BuildContext context) {
    state = state.copyWith(error: null);
    
    switch (state.currentStep) {
      case 0:
        return true; // Document info step - no validation
      case 1:
        if (state.customerName.isEmpty || state.completeAddress.isEmpty || state.contactPerson.isEmpty || state.mobileNumber.isEmpty) {
          state = state.copyWith(error: 'Please fill in all customer details.');
          return false;
        }
        return true;
      case 2:
        if (state.descriptionItems.isEmpty) {
          state = state.copyWith(error: 'Please add at least one item description.');
          return false;
        }
        return true;
      case 3:
        return true; // GST step - no validation
      case 4:
        if (state.documentType == 'Agreement' && state.customerSignature == null && (state.submittedAgreement?.customerSignatureUrl?.isEmpty ?? true)) {
          state = state.copyWith(error: 'Customer signature is required for AMC Agreements.');
          return false;
        }
        return true;
      default:
        return true;
    }
  }

  Future<bool> submitAgreement(String selectedDocType) async {
    state = state.copyWith(
      isSubmitting: true,
      error: null,
      documentType: selectedDocType,
    );

    try {
      final isQuotation = selectedDocType == 'Quotation';
      final hasSignature = state.customerSignature != null || 
          (state.submittedAgreement?.customerSignatureUrl?.isNotEmpty ?? false);

      if (selectedDocType == 'Agreement' && !hasSignature) {
        state = state.copyWith(
          isSubmitting: false,
          error: 'Customer signature is required for AMC Agreements.',
        );
        return false;
      }

      final agreementPayload = state.toAgreementModel(status: 'submitted');
      
      AgreementModel result;
      if (state.id != null) {
        result = await _repository.updateAgreement(
          id: state.id!,
          agreement: agreementPayload,
          signatureFile: state.customerSignature,
        );
      } else {
        result = await _repository.createAgreement(
          agreement: agreementPayload,
          signatureFile: state.customerSignature,
        );
      }

      await _agreementsNotifier.refresh();

      state = state.copyWith(
        isSubmitting: false,
        submittedAgreement: result,
        status: 'submitted',
      );
      return true;
    } catch (e) {
      state = state.copyWith(
        isSubmitting: false,
        error: e.toString(),
      );
      return false;
    }
  }
}

final agreementWizardProvider = StateNotifierProvider.autoDispose<AgreementWizardNotifier, AgreementWizardState>((ref) {
  final repo = ref.watch(agreementRepositoryProvider);
  final agreements = ref.read(agreementsProvider.notifier);
  return AgreementWizardNotifier(repo, agreements);
});
