name: Keep Render Awake

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "7/12 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
      - run: date

      - run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            https://dieseltechnicalsolutions.onrender.com/api/ping